version: '3'

services:
  message-service:
    image: message-service:latest

  user-service:
    image: user-service:latest
    command:
      #    - "--mysql.address=172.18.0.1"
    - "--mysql.address=192.168.137.1"

  user-edge-service:
    image: user-edge-service:latest
    links:
    - user-service
    - message-service
    command:
      #    - "--redis.address=172.18.0.1"
    - "--redis.address=192.168.137.1"

  course-service:
    image: course-service:latest
    links:
    - user-service
    command:
      #      - "--mysql.address=172.18.0.1"
      #      - "--zookeeper.address=172.18.0.1"
    - "--mysql.address=192.168.137.1"
    - "--dubbo.registry.address=zookeeper://192.168.137.1:2181"

  course-edge-service:
    image: course-edge-service:latest
    links:
    - user-edge-service
    command:
      #    - "--zookeeper.address=172.18.0.1"
    - "--zookeeper.address=192.168.137.1"

  api-gateway-zuul:
    image: api-gateway-zuul:latest
    links:
    - user-edge-service
    - course-edge-service
    ports:
    - 80:80